"""initial schema

Revision ID: c1adf89c9b67
Revises: 
Create Date: 2026-07-31 12:02:55.391744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1adf89c9b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.String(length=20), nullable=False),
    sa.Column('deployment', sa.Text(), nullable=False),
    sa.Column('input_config', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('total_msg', sa.Integer(), nullable=True),
    sa.Column('validation_rate', sa.Float(), nullable=True),
    sa.Column('test_rate', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendly_name', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=8), nullable=False),
    sa.Column('mqtt_address', sa.Text(), nullable=False),
    sa.Column('mqtt_port', sa.Integer(), nullable=False),
    sa.Column('mqtt_username', sa.Text(), nullable=False),
    sa.Column('mqtt_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friendly_name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('ml_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('imports', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('distributed', sa.Boolean(), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('framework', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['father_id'], ['ml_model.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('father_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('configuration_ml_models',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('ml_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('configuration_id', 'ml_model_id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('tf_kwargs_fit', sa.String(length=100), nullable=False),
    sa.Column('tf_kwargs_val', sa.String(length=100), nullable=False),
    sa.Column('pth_kwargs_fit', sa.String(length=100), nullable=False),
    sa.Column('pth_kwargs_val', sa.String(length=100), nullable=False),
    sa.Column('conf_mat_settings', sa.Boolean(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('optimizer', sa.Text(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('loss', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('incremental', sa.Boolean(), nullable=False),
    sa.Column('indefinite', sa.Boolean(), nullable=False),
    sa.Column('stream_timeout', sa.Integer(), nullable=True),
    sa.Column('monitoring_metric', sa.Text(), nullable=True),
    sa.Column('change', sa.Text(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('unsupervised', sa.Boolean(), nullable=False),
    sa.Column('unsupervised_rounds', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('federated', sa.Boolean(), nullable=False),
    sa.Column('agg_rounds', sa.Integer(), nullable=True),
    sa.Column('min_data', sa.Integer(), nullable=True),
    sa.Column('agg_strategy', sa.String(length=20), nullable=False),
    sa.Column('data_restriction', sa.JSON(), nullable=False),
    sa.Column('blockchain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('train_metrics', sa.JSON(), nullable=True),
    sa.Column('val_metrics', sa.JSON(), nullable=True),
    sa.Column('test_metrics', sa.JSON(), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('training_time', sa.Float(), nullable=True),
    sa.Column('trained_model_path', sa.String(length=255), nullable=False),
    sa.Column('confusion_mat_img_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_result_id', sa.Integer(), nullable=True),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('input_format', sa.String(length=20), nullable=False),
    sa.Column('input_config', sa.Text(), nullable=False),
    sa.Column('input_topic', sa.Text(), nullable=False),
    sa.Column('output_topic', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('limit', sa.Float(), nullable=True),
    sa.Column('output_upper', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('external_host', sa.Text(), nullable=True),
    sa.Column('input_kafka_broker', sa.Text(), nullable=True),
    sa.Column('output_kafka_broker', sa.Text(), nullable=True),
    sa.Column('upper_kafka_broker', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_result_id'], ['training_result.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference')
    op.drop_table('training_result')
    op.drop_table('deployment')
    op.drop_table('configuration_ml_models')
    op.drop_table('ml_model')
    op.drop_table('iot_device')
    op.drop_table('datasource')
    op.drop_table('configuration')
    # ### end Alembic commands ###
