apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../v1.3"

components:
  - "../components/gpu-executor-images"

configMapGenerator:
  - name: kafkaml-configmap
    behavior: merge
    literals:
      - tensorflow.training.image=ertis/kafka-ml-tensorflow_model_training-gpu:v1.3
      - tensorflow.inference.image=ertis/kafka-ml-tensorflow_model_inference-gpu:v1.3
      - pytorch.training.image=ertis/kafka-ml-pytorch_model_training-gpu:v1.3
      - pytorch.inference.image=ertis/kafka-ml-pytorch_model_inference-gpu:v1.3
