"""add ml_model created_at and updated_at

Revision ID: ba0b7ea5c381
Revises: c1adf89c9b67
Create Date: 2026-08-07 19:21:03.238021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba0b7ea5c381'
down_revision: Union[str, None] = 'c1adf89c9b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (CURRENT_TIMESTAMP is UTC in
    # sqlite) - dropped again right after so future inserts still rely on
    # the ORM-side `default=utcnow`, matching every other timestamp column
    # in this schema.
    op.add_column(
        'ml_model',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.add_column(
        'ml_model',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    with op.batch_alter_table('ml_model') as batch_op:
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ml_model', 'updated_at')
    op.drop_column('ml_model', 'created_at')
    # ### end Alembic commands ###
