resources:
  - "../v1.1"

components:
  - "../components/gpu-executor-images"

configMapGenerator:
  - name: kafkaml-configmap
    behavior: merge
    literals:
      - tensorflow.training.image=ertis/kafka-ml-tensorflow_model_training-gpu:v1.1
      - tensorflow.inference.image=ertis/kafka-ml-tensorflow_model_inference-gpu:v1.1
      - pytorch.training.image=ertis/kafka-ml-pytorch_model_training-gpu:v1.1
      - pytorch.inference.image=ertis/kafka-ml-pytorch_model_inference-gpu:v1.1
